#!/usr/bin/env python3
"""Build the held-out BSM table: AUROC and TPR at 10% FPR on the CASE signals.

Reads the result files README stage 3 writes for the collide_v2 CASE production
(`case_v2_ad.sub` for the encoders, `case_v2_raw.sub` for the raw-feature baseline):
20,000 events per signal, scored against the QCD reference of the proxy signals.
Each cell is the mean and sample standard deviation (ddof = 1) over the five seeds of
the run. A standard deviation that rounds to zero is printed as one unit of the last
digit, as in the proxy table. The best value of each column is set in bold.

Usage:
    python paper/make_heldout_bsm_table.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

DEFAULT_ROOT = Path("/eos/user/d/dgenoves/anomaly_pipeline/new_exp/ad_results_case_v2")
DEFAULT_OUT = Path(__file__).resolve().parent / "sections" / "heldout_bsm_table.tex"
RESULT = "random/result_case_v2.json"   # the paper's selection (scripts/select_case_events.py)

# Seed sets differ by model, as in scripts/infer_new_signals.py.
MODELS = {
    "supcon": ("SupCon", [7, 42, 137, 1337, 31337]),
    "simclr": ("SimCLR", [7, 42, 137, 1337, 31337]),
    "vcreg":  ("VCReg",  [0, 1, 2, 3, 4]),
    "vicreg": ("VICReg", [7, 42, 12345, 1337, 31337]),
}
RAW_SEEDS = [7, 42, 137, 1337, 31337]
DMODELS = [32, 64, 128, 256]

# Labels in the CASE dataset (the order of `to_classify` in anomaly_case_v2_smnorm).
SIGNALS = [
    (1, r"$H \to aa \to 4b$"),
    (2, r"$H \to aa \to 4\tau$"),
    (3, r"$Z' \to n(\mu\mu)$"),
]

CAPTION = (r"AUROC and signal efficiency at 10\% background acceptance (mean $\pm$ std over "
           r"5 seeds). For each process, 20{,}000 events are drawn at random from a dedicated "
           r"production of 50{,}000, matching the test statistics of the proxy signals of "
           r"Table~\ref{tab:heldout_proxies}; the QCD reference is the same as for $HH \to 4b$.")


def seed_stats(paths: list[Path], label: int) -> tuple[float, float, float, float]:
    """(AUROC mean, std, TPR mean, std) over the seeds, TPR in percent."""
    res = [json.loads(p.read_text())["per_signal"] for p in paths]
    auc = np.array([r[f"auroc_cls{label}"] for r in res])
    tpr = np.array([r[f"tpr_fpr10_cls{label}"] for r in res]) * 100
    return auc.mean(), auc.std(ddof=1), tpr.mean(), tpr.std(ddof=1)


def fmt(mean: float, std: float, dec: int) -> str:
    std = round(std, dec) or 10 ** -dec
    return f"{mean:.{dec}f} \\pm {std:.{dec}f}"


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--root", type=Path, default=DEFAULT_ROOT,
                   help="ad_results_case_v2 directory of the scoring jobs")
    p.add_argument("--output", type=Path, default=DEFAULT_OUT)
    args = p.parse_args()

    runs = {("raw", None): [args.root / "raw" / f"seed_{s}" / RESULT for s in RAW_SEEDS]}
    for m, (_, seeds) in MODELS.items():
        for d in DMODELS:
            run = f"{m}_12class_nosparse_dmodel{d}_cern"
            runs[(m, d)] = [args.root / run / f"encoder_seed_{s}" / RESULT for s in seeds]
    missing = [str(f) for fs in runs.values() for f in fs if not f.exists()]
    if missing:
        print(f"{len(missing)} result files missing, e.g. {missing[0]}")
        return 1

    rows = {k: {lbl: seed_stats(fs, lbl) for lbl, _ in SIGNALS} for k, fs in runs.items()}
    best = {(lbl, col): max(rows, key=lambda k: rows[k][lbl][col])
            for lbl, _ in SIGNALS for col in (0, 2)}

    def cells(key):
        out = []
        for lbl, _ in SIGNALS:
            a_mu, a_sd, t_mu, t_sd = rows[key][lbl]
            for col, txt in ((0, fmt(a_mu, a_sd, 3)), (2, fmt(t_mu, t_sd, 1))):
                out.append(f"$\\mathbf{{{txt}}}$" if best[(lbl, col)] == key else f"${txt}$")
        return " & ".join(out)

    heads = " & ".join(f"\\multicolumn{{2}}{{c}}{{{name}}}" for _, name in SIGNALS)
    L = [
        "% Auto-generated by paper/make_heldout_bsm_table.py --- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        f"\\caption{{{CAPTION}}}",
        r"\label{tab:heldout_bsm}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{llcccccc}",
        r"\toprule",
        f" & & {heads} \\\\",
        r"\cmidrule(lr){3-4}\cmidrule(lr){5-6}\cmidrule(lr){7-8}",
        r"Model & $d_{\text{model}}$ & AUROC & TPR@10\% & AUROC & TPR@10\% & AUROC & TPR@10\% \\",
        r"\midrule",
        f"Raw AE & --- & {cells(('raw', None))} \\\\",
    ]
    for m, (name, _) in MODELS.items():
        L.append(r"\midrule")
        for i, d in enumerate(DMODELS):
            lead = f"\\multirow{{4}}{{*}}{{{name}}}" if i == 0 else ""
            L.append(f"{lead} & {d} & {cells((m, d))} \\\\")
    L += [r"\bottomrule", r"\end{tabular}%", "}", r"\end{table}"]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(L) + "\n")
    print(f"Saved {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
