#!/usr/bin/env python3
"""Build the side-by-side Wasserstein ranking table for Section 4.3.

Step 04 writes one standalone `table` float per signal. Two floats cannot be placed
on the same line by LaTeX, and separately they invite the reader to compare the two
signals by flipping pages. This merges them into a single float holding two
minipages, so HH->4b and HV Z'->mumu sit next to each other and the leading
observable of each is read in one glance.

Three things are fixed here that the auto-generated fragments get wrong for print:
observables are emitted as maths (`n_b`, not `n_bjets`), distances are printed to a
fixed two decimals instead of `%.3g` (which mixes `2.7` with `2.73` down a column),
and the signal names are LaTeX rather than the internal slugs.

The QCD column is the control. It is an em dash wherever the component holds too
few QCD events for the distance to be defined --- which is itself the point in C2,
where a leptonic signal lands in a region the trained normality never covered.

Usage:
    python paper/make_wasserstein_table.py
"""

from __future__ import annotations

import csv
from pathlib import Path

XP = Path("/eos/user/d/dgenoves/anomaly_pipeline/xai_paper/rank_k7_sm")
OUT = Path(__file__).resolve().parent / "sections" / "xai" / "wasserstein_side_by_side.tex"

# Match the notation of Table 3 in the main text.
MATHS = {
    "HT": r"$H_T$",
    "MET": r"MET",
    "n_jets": r"$n_\mathrm{jets}$",
    "n_bjets": r"$n_b$",
    "n_leptons": r"$n_\mathrm{leptons}$",
    "Mjj": r"$M_{jj}$",
    "deta_jj": r"$\Delta\eta_{jj}$",
    "MT": r"$M_T$",
}

SIGNALS = [
    ("hh4b", r"$HH \to 4b$"),
    ("hvdilep", r"HV $Z' \to \mu\mu$"),
]


def num(raw: str) -> str:
    if raw in ("", "nan", "NaN"):
        return "---"
    return f"{float(raw):.2f}"


def block(slug: str) -> list[str]:
    rows = list(csv.DictReader((XP / slug / "wasserstein_rank.csv").open()))
    ranked = [r for r in rows if r["rank"] not in ("", None)]
    by_comp: dict[int, list] = {}
    for r in ranked:
        by_comp.setdefault(int(r["component"]), []).append(r)

    lines = [
        r"\begin{tabular}{llrr}",
        r"\toprule",
        r"& Observable & $W_1^{\mathrm{SM}}$ & $W_1^{\mathrm{QCD}}$ \\",
        r"\midrule",
    ]
    for comp in sorted(by_comp, key=lambda c: int(by_comp[c][0]["rank"])):
        blk = sorted(by_comp[comp], key=lambda r: int(r["rank"]))
        for i, r in enumerate(blk):
            head = rf"C{comp}" if i == 0 else ""
            obs = MATHS.get(r["variable"], r["variable"])
            sm, qcd = num(r["W1_sm"]), num(r["W1_qcd"])
            if i == 0:  # the leading observable carries the claim
                obs, sm = rf"\textbf{{{obs}}}", rf"\textbf{{{sm}}}"
            lines.append(rf"{head} & {obs} & {sm} & {qcd} \\")
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines += [r"\end{tabular}"]
    return lines


def main() -> int:
    out = [
        r"% Auto-generated by paper/make_wasserstein_table.py --- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Local discriminating power of the high-level observables within the "
        r"mixture components that hold the AE-flagged signal, for $HH \to 4b$ (left) and "
        r"HV $Z' \to \mu\mu$ (right). $W_1^{\mathrm{SM}}$ is the Wasserstein-1 distance "
        r"between the flagged signal and the local Standard Model background, standardised "
        r"by each observable's global standard deviation so that rows are dimensionless and "
        r"comparable; observables are ranked by it and the leading one is set in bold. "
        r"$W_1^{\mathrm{QCD}}$, computed against the local QCD background --- the "
        r"autoencoder's trained normality --- is a control, and is undefined in C2, which "
        r"contains a single QCD event.}",
        r"\label{tab:wasserstein_rank}",
    ]
    for i, (slug, name) in enumerate(SIGNALS):
        out.append(r"\begin{minipage}[t]{0.48\textwidth}")
        out.append(r"\centering")
        out.append(rf"\textbf{{{name}}}\\[2pt]")
        out += block(slug)
        out.append(r"\end{minipage}")
        if i == 0:
            out.append(r"\hfill")
    out += [r"\end{table}", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"Saved {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
